# Generated by Django 4.1.12 on 2025-02-26 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0003_employee_address_employee_age_and_more'),
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(verbose_name='تاريخ الترقية')),
                ('course_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الدورة')),
                ('promotion_type', models.CharField(choices=[('عادية', 'عادية'), ('استثنائية', 'استثنائية')], default='عادية', max_length=20, verbose_name='نوع الترقية')),
                ('course_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بدء الفرقة')),
                ('course_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الفرقة')),
                ('training_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة التدريبية')),
                ('result', models.CharField(blank=True, choices=[('ناجح', 'ناجح'), ('راسب', 'راسب'), ('إلغاء', 'إلغاء')], max_length=20, null=True, verbose_name='النتيجة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='em_data.employee', verbose_name='الموظف')),
                ('from_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_promotions', to='ranks.rank', verbose_name='من درجة')),
                ('to_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_promotions', to='ranks.rank', verbose_name='إلى درجة')),
            ],
            options={
                'verbose_name': 'ترقية',
                'verbose_name_plural': 'الترقيات',
                'ordering': ['-promotion_date'],
            },
        ),
    ]
