# Generated by Django 4.1.12 on 2025-03-14 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0005_employee_nots'),
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField(verbose_name='تاريخ الترقية')),
                ('promotion_course_number', models.CharField(max_length=50, verbose_name='رقم دورة الترقية')),
                ('training_start_date', models.DateField(verbose_name='تاريخ بداية الدورة')),
                ('training_end_date', models.DateField(verbose_name='تاريخ نهاية الدورة')),
                ('training_course_number', models.CharField(max_length=50, verbose_name='رقم الدورة التأهيلية')),
                ('training_location', models.CharField(max_length=255, verbose_name='مكان انعقاد الدورة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='em_data.employee', verbose_name='الموظف')),
                ('from_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_from', to='ranks.rank', verbose_name='الدرجة السابقة')),
                ('to_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='ranks.rank', verbose_name='الدرجة الجديدة')),
            ],
            options={
                'verbose_name': 'ترقية',
                'verbose_name_plural': 'الترقيات',
                'ordering': ['-promotion_date'],
            },
        ),
    ]
