# Generated by Django 4.1.12 on 2025-03-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarkyat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promotion_course_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم دورة الترقية'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='training_course_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الدورة التأهيلية'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='training_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الدورة'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='training_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان انعقاد الدورة'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='training_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الدورة'),
        ),
    ]
