# Generated by Django 4.1.12 on 2025-03-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarkyat', '0002_alter_promotion_promotion_course_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='promotion_type',
            field=models.CharField(blank=True, choices=[('normal', 'عادية'), ('exceptional', 'استثنائية'), ('cadre', 'كادر أمناء')], max_length=20, null=True, verbose_name='نوع الترقية'),
        ),
    ]
