# Generated by Django 4.1.12 on 2025-03-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['order'], 'verbose_name': 'الدرجة', 'verbose_name_plural': 'الدرجات'},
        ),
        migrations.AddField(
            model_name='rank',
            name='is_active',
            field=models.BooleanField(default=True, help_text='حدد ما إذا كانت الدرجة مستخدمة حاليًا', verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='rank',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='رقم يحدد ترتيب الدرجة (1 = درجة أدنى)', verbose_name='الترتيب'),
        ),
        migrations.AddField(
            model_name='rank',
            name='rank_type',
            field=models.CharField(choices=[('primary', 'درجة أولى'), ('police_officer', 'أمين شرطة'), ('security_assistant', 'معاون أمن')], default='', help_text='اختر نوع الدرجة (أولى، أمين شرطة، معاون أمن)', max_length=20, verbose_name='نوع الدرجة'),
            preserve_default=False,
        ),
    ]
