# Generated by Django 5.1.4 on 2025-09-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0010_alter_employee_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='السنة')),
                ('score', models.PositiveIntegerField(help_text='من 1 إلى 100', verbose_name='الدرجة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_reports', to='em_data.employee')),
            ],
            options={
                'db_table': 'secret_reports',
                'ordering': ['-year'],
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
