# Generated by Django 5.1.4 on 2025-10-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretreport',
            name='score',
            field=models.PositiveIntegerField(blank=True, help_text='من 1 إلى 100', null=True, verbose_name='الدرجة'),
        ),
    ]
