# Generated by Django 5.1.4 on 2026-01-14 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0010_alter_employee_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'نوع الجزاء',
                'verbose_name_plural': 'أنواع الجزاءات',
            },
        ),
        migrations.CreateModel(
            name='ViolationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح التصنيف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'verbose_name': 'تصنيف المخالفة',
                'verbose_name_plural': 'تصنيفات المخالفات',
            },
        ),
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم المخالفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_types', to='penalties.violationcategory', verbose_name='التصنيف')),
                ('default_penalty_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltylevel', verbose_name='نوع الجزاء الافتراضي')),
            ],
            options={
                'verbose_name': 'نوع المخالفة',
                'verbose_name_plural': 'أنواع المخالفات',
            },
        ),
        migrations.CreateModel(
            name='PenaltyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_date', models.DateField(verbose_name='تاريخ الجزاء')),
                ('violation_description', models.TextField(blank=True, null=True, verbose_name='وصف المخالفة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('absence_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='بند الغياب')),
                ('attendance_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='بند الحضور')),
                ('form_image', models.ImageField(blank=True, null=True, upload_to='penalty_forms/', verbose_name='صورة الأورنيك')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المدخل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='em_data.employee', verbose_name='الفرد')),
                ('penalty_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltylevel', verbose_name='نوع الجزاء')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.violationcategory', verbose_name='التصنيف')),
                ('violation_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.violationtype', verbose_name='نوع المخالفة')),
            ],
            options={
                'verbose_name': 'سجل الجزاء',
                'verbose_name_plural': 'سجلات الجزاءات',
            },
        ),
    ]
