# Generated by Django 5.1.4 on 2026-01-14 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violationtype',
            name='default_penalty_level',
        ),
        migrations.AddField(
            model_name='violationtype',
            name='description_template',
            field=models.TextField(blank=True, help_text='يمكنك استخدام {date} وسيتم استبداله بتاريخ اليوم', null=True, verbose_name='قالب وصف المخالفة'),
        ),
        migrations.AddField(
            model_name='violationtype',
            name='is_absence',
            field=models.BooleanField(default=False, verbose_name='هل هي مخالفة غياب؟'),
        ),
        migrations.CreateModel(
            name='PenaltyApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم الجزاء الموقع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('penalty_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_penalties', to='penalties.penaltylevel', verbose_name='نوع الجزاء المرتبط')),
            ],
            options={
                'verbose_name': 'الجزاء الموقع',
                'verbose_name_plural': 'الجزاءات الموقعة',
            },
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='penalty_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltyapplied', verbose_name='الجزاء الموقع'),
        ),
    ]
