# Generated by Django 5.1.4 on 2026-01-15 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0002_remove_violationtype_default_penalty_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='العنوان التعريفي')),
                ('text', models.TextField(verbose_name='نص المخالفة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('violation_type', models.ForeignKey(blank=True, help_text='اختياري: لربط النص بنوع مخالفة محدد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.violationtype', verbose_name='نوع المخالفة المرتبط')),
            ],
            options={
                'verbose_name': 'نص مخالفة جاهز',
                'verbose_name_plural': 'نصوص مخالفات جاهزة',
            },
        ),
    ]
