# Generated by Django 5.1.4 on 2026-01-17 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0003_violationpreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penaltyapplied',
            options={},
        ),
        migrations.AlterModelOptions(
            name='penaltylevel',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='penaltyrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='violationcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='violationpreset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='violationtype',
            options={},
        ),
        migrations.RemoveField(
            model_name='penaltyapplied',
            name='description',
        ),
        migrations.RemoveField(
            model_name='penaltyapplied',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='penaltylevel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='penaltylevel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='absence_code',
        ),
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='attendance_code',
        ),
        migrations.RemoveField(
            model_name='penaltyrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='violationcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='violationcategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='violationpreset',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='violationtype',
            name='is_active',
        ),
        migrations.AddField(
            model_name='penaltylevel',
            name='is_major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='penaltylevel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='erase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='erase_decision_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='erase_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='erase_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penaltyapplied',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='penaltyapplied',
            name='penalty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to='penalties.penaltylevel'),
        ),
        migrations.AlterField(
            model_name='penaltylevel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.violationcategory'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='form_image',
            field=models.ImageField(blank=True, null=True, upload_to='penalty_forms/'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='penalty_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltyapplied'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='penalty_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='penalty_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltylevel'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='violation_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='violation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.violationtype'),
        ),
        migrations.AlterField(
            model_name='violationcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='violationpreset',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='violationpreset',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='violationpreset',
            name='violation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='penalties.violationtype'),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='penalties.violationcategory'),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='description_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='is_absence',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='PenaltyAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('penalty_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='penalties.penaltyapplied')),
            ],
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='penalty_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltyamount'),
        ),
    ]
