# Generated by Django 5.1.4 on 2026-01-18 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0010_alter_employee_operation'),
        ('penalties', '0004_alter_penaltyapplied_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penaltyamount',
            options={'verbose_name': 'مقدار الجزاء', 'verbose_name_plural': 'مقادير الجزاءات'},
        ),
        migrations.AlterModelOptions(
            name='penaltyapplied',
            options={'verbose_name': 'الجزاء الموقع', 'verbose_name_plural': 'الجزاءات الموقعة'},
        ),
        migrations.AlterModelOptions(
            name='penaltylevel',
            options={'verbose_name': 'نوع الجزاء', 'verbose_name_plural': 'أنواع الجزاءات'},
        ),
        migrations.AlterModelOptions(
            name='penaltyrecord',
            options={'verbose_name': 'سجل الجزاء', 'verbose_name_plural': 'سجلات الجزاءات'},
        ),
        migrations.AlterModelOptions(
            name='violationcategory',
            options={'verbose_name': 'تصنيف المخالفة', 'verbose_name_plural': 'تصنيفات المخالفات'},
        ),
        migrations.AlterModelOptions(
            name='violationpreset',
            options={'verbose_name': 'نص مخالفة جاهز', 'verbose_name_plural': 'نصوص مخالفات جاهزة'},
        ),
        migrations.AlterModelOptions(
            name='violationtype',
            options={'verbose_name': 'نوع المخالفة', 'verbose_name_plural': 'أنواع المخالفات'},
        ),
        migrations.AddField(
            model_name='penaltyamount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='penaltyamount',
            name='value',
            field=models.IntegerField(default=1, verbose_name='القيمة'),
        ),
        migrations.AddField(
            model_name='penaltyapplied',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='penaltyapplied',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='penaltylevel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AddField(
            model_name='penaltylevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='absence_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بند الغياب'),
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='attendance_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='بند الحضور'),
        ),
        migrations.AddField(
            model_name='penaltyrecord',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المدخل'),
        ),
        migrations.AddField(
            model_name='violationcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='شرح التصنيف'),
        ),
        migrations.AddField(
            model_name='violationcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='violationpreset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AddField(
            model_name='violationtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعل'),
        ),
        migrations.AlterField(
            model_name='penaltyamount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم مقدار الجزاء'),
        ),
        migrations.AlterField(
            model_name='penaltyamount',
            name='penalty_applied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='penalties.penaltyapplied', verbose_name='الجزاء الموقع'),
        ),
        migrations.AlterField(
            model_name='penaltyapplied',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم الجزاء الموقع'),
        ),
        migrations.AlterField(
            model_name='penaltyapplied',
            name='penalty_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_penalties', to='penalties.penaltylevel', verbose_name='نوع الجزاء المرتبط'),
        ),
        migrations.AlterField(
            model_name='penaltylevel',
            name='is_major',
            field=models.BooleanField(default=False, verbose_name='جزاء كبرى؟'),
        ),
        migrations.AlterField(
            model_name='penaltylevel',
            name='name',
            field=models.CharField(max_length=50, verbose_name='اسم النوع'),
        ),
        migrations.AlterField(
            model_name='penaltylevel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.violationcategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='em_data.employee', verbose_name='الفرد'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='erase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ محو الجزاء'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='erase_decision_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم قرار المحو'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='erase_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات المحو'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='erase_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة المحو'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='form_image',
            field=models.ImageField(blank=True, null=True, upload_to='penalty_forms/', verbose_name='صورة الأورنيك'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='penalty_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltyamount', verbose_name='مقدار الجزاء'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='penalty_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltyapplied', verbose_name='الجزاء الموقع'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='penalty_date',
            field=models.DateField(verbose_name='تاريخ الجزاء'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='penalty_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.penaltylevel', verbose_name='نوع الجزاء'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='violation_description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المخالفة'),
        ),
        migrations.AlterField(
            model_name='penaltyrecord',
            name='violation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.violationtype', verbose_name='نوع المخالفة'),
        ),
        migrations.AlterField(
            model_name='violationcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم التصنيف'),
        ),
        migrations.AlterField(
            model_name='violationpreset',
            name='name',
            field=models.CharField(max_length=150, verbose_name='العنوان التعريفي'),
        ),
        migrations.AlterField(
            model_name='violationpreset',
            name='text',
            field=models.TextField(verbose_name='نص المخالفة'),
        ),
        migrations.AlterField(
            model_name='violationpreset',
            name='violation_type',
            field=models.ForeignKey(blank=True, help_text='اختياري: لربط النص بنوع مخالفة محدد', null=True, on_delete=django.db.models.deletion.SET_NULL, to='penalties.violationtype', verbose_name='نوع المخالفة المرتبط'),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_types', to='penalties.violationcategory', verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='description_template',
            field=models.TextField(blank=True, help_text='يمكنك استخدام {date} وسيتم استبداله بتاريخ اليوم', null=True, verbose_name='قالب وصف المخالفة'),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='is_absence',
            field=models.BooleanField(default=False, verbose_name='هل هي مخالفة غياب؟'),
        ),
        migrations.AlterField(
            model_name='violationtype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم المخالفة'),
        ),
    ]
