# Generated by Django 5.1.4 on 2026-02-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0005_alter_penaltyamount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penaltyamount',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='القيمة'),
        ),
    ]
