# Generated by Django 5.1.4 on 2026-02-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0006_alter_penaltyamount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyrecord',
            name='deduct_absence_days',
            field=models.BooleanField(default=False, verbose_name='مع خصم أيام الغياب'),
        ),
    ]
