# Generated by Django 4.1.12 on 2025-02-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'institutes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('rank', models.CharField(blank=True, choices=[('أمين شرطة ممتاز أول', 'أمين شرطة ممتاز أول'), ('أمين شرطة ممتاز ثان', 'أمين شرطة ممتاز ثان'), ('أمين شرطة ممتاز', 'أمين شرطة ممتاز'), ('أمين شرطة أول', 'أمين شرطة أول'), ('أمين شرطة ثان', 'أمين شرطة ثان'), ('أمين شرطة ثالث', 'أمين شرطة ثالث'), ('مساعد شرطة ممتاز', 'مساعد شرطة ممتاز'), ('مساعد شرطة أول', 'مساعد شرطة أول'), ('مساعد شرطة ثان', 'مساعد شرطة ثان'), ('مساعد شرطة ثالث', 'مساعد شرطة ثالث'), ('مراقب شرطة ممتاز', 'مراقب شرطة ممتاز'), ('مراقب شرطة أول', 'مراقب شرطة أول'), ('مراقب شرطة ثان', 'مراقب شرطة ثان'), ('مراقب شرطة ثالث', 'مراقب شرطة ثالث'), ('مندوب شرطة ممتاز', 'مندوب شرطة ممتاز'), ('مندوب شرطة أول', 'مندوب شرطة أول'), ('مندوب شرطة ثان', 'مندوب شرطة ثان'), ('مندوب شرطة ثالث', 'مندوب شرطة ثالث'), ('رقيب أول', 'رقيب أول'), ('رقيب', 'رقيب'), ('عريف', 'عريف'), ('جندي', 'جندي'), ('معاون أمن ممتاز أول', 'معاون أمن ممتاز أول'), ('معاون أمن ممتاز ثان', 'معاون أمن ممتاز ثان'), ('معاون أمن ممتاز', 'معاون أمن ممتاز'), ('معاون أمن أول', 'معاون أمن أول'), ('معاون أمن ثان', 'معاون أمن ثان'), ('معاون أمن ثالث', 'معاون أمن ثالث')], max_length=255, null=True)),
                ('sort_number', models.IntegerField(blank=True, null=True)),
                ('police_number', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_number', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_appointment', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='em_data.institute')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
