# Generated by Django 4.1.12 on 2025-02-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0003_employee_address_employee_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_retirement',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التقاعد'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
    ]
