# Generated by Django 4.1.12 on 2025-02-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0004_alter_employee_age_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nots',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
