# Generated by Django 5.1.6 on 2025-04-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0005_employee_nots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='total_leave',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
