# Generated by Django 5.1.6 on 2025-04-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0006_alter_employee_total_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rahatcounter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
