# Generated by Django 5.1.4 on 2025-05-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0007_alter_employee_rahatcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='idcard_expir',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء بطاقة الهوية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='idcard_social',
            field=models.CharField(blank=True, choices=[('أعزب', 'أعزب'), ('متزوج', 'متزوج'), ('مطلق', 'مطلق')], max_length=20, null=True, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='idcard_work',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة'),
        ),
    ]
