# Generated by Django 5.1.4 on 2025-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0008_employee_idcard_expir_employee_idcard_social_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='idcard_work',
            field=models.CharField(blank=True, choices=[('درجة شرطية', 'درجة شرطية'), ('مهنة مدنية', 'مهنة مدنية'), ('طالب/طالبة', 'طالب/طالبة'), ('أخرى', 'أخرى')], max_length=20, null=True, verbose_name='المهنة'),
        ),
    ]
