# Generated by Django 5.1.4 on 2026-02-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0010_alter_employee_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='سائق'),
        ),
    ]
