# Generated by Django 5.1.4 on 2026-02-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0011_employee_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='optional',
            field=models.BooleanField(default=False, verbose_name='optional'),
        ),
    ]
