# Generated by Django 5.1.4 on 2026-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0012_employee_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='optional',
            new_name='dryfood',
        ),
    ]
