# Generated by Django 5.1.4 on 2026-02-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0013_remove_employee_optional_employee_dryfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dryfood',
            field=models.BooleanField(default=False, verbose_name='dryfood'),
        ),
    ]
