# Generated by Django 5.1.4 on 2026-02-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0015_alter_employee_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='operation',
            field=models.CharField(blank=True, choices=[('لم يحدد', 'لم يحدد'), ('السبت', 'السبت'), ('الأحد', 'الأحد'), ('الاثنين', 'الاثنين'), ('الثلاثاء', 'الثلاثاء'), ('الأربعاء', 'الأربعاء'), ('الخميس', 'الخميس'), ('الجمعة', 'الجمعة'), ('عمل يومي', 'عمل يومي'), ('انتداب', 'انتداب'), ('خاصه', 'خاصه'), ('ج وضع', 'ج وضع'), ('قرار66', 'قرار66')], default='لم يحدد', max_length=20, null=True),
        ),
    ]
