# Generated by Django 5.1.4 on 2026-02-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0016_alter_employee_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mony_out',
            field=models.BooleanField(default=False, verbose_name='مستحقات خارج الإدارة'),
        ),
    ]
