# Generated by Django 5.1.4 on 2026-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0017_employee_mony_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='seniority_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='ترتيب الأقدمية المطلقة'),
        ),
    ]
