# Generated by Django 5.1.4 on 2026-03-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0018_employee_seniority_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الدفعة'),
        ),
    ]
