# Generated by Django 5.1.4 on 2026-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0019_employee_batch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_type', models.CharField(choices=[('internal', 'نقل داخلي'), ('external', 'نقل خارجي')], max_length=20, verbose_name='نوع النقل')),
                ('year', models.IntegerField(verbose_name='العام')),
                ('police_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشرطة')),
                ('name', models.CharField(max_length=255, verbose_name='الأسم')),
                ('attachment_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='تاريخ الحاقة بالإدارة')),
                ('transferred_from', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المنقول منها')),
                ('transferred_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المنقول اليها')),
                ('decision_details', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم وتاريخ القرار')),
                ('execution_date', models.CharField(blank=True, max_length=100, null=True, verbose_name='تاريخ التنفيذ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سجل نقل',
                'verbose_name_plural': 'سجلات النقل',
                'db_table': 'transfer_records',
                'ordering': ['id'],
            },
        ),
    ]
