# Generated by Django 5.1.4 on 2026-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0020_transferrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLocation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم الجهة')),
                ('location_type', models.CharField(choices=[('internal', 'داخلي'), ('external', 'خارجي')], max_length=20, verbose_name='نوع النقل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جهة نقل',
                'verbose_name_plural': 'جهات النقل',
                'db_table': 'transfer_locations',
                'ordering': ['name'],
                'unique_together': {('name', 'location_type')},
            },
        ),
    ]
