# Generated by Django 5.1.4 on 2026-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0021_transferlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferrecord',
            name='decision_details',
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='decision_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تاريخ القرار'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='decision_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم القرار'),
        ),
    ]
