# Generated by Django 5.1.4 on 2026-03-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0022_remove_transferrecord_decision_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف الوظيفي'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المسمى الوظيفي'),
        ),
    ]
