# Generated by Django 5.1.4 on 2026-03-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0023_employee_job_description_employee_job_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الآلة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الآلة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='instruments/', verbose_name='صورة الآلة')),
                ('category', models.CharField(choices=[('خشبية', 'خشبية'), ('نحاسية', 'نحاسية'), ('وترية', 'وترية'), ('إيقاعية', 'إيقاعية'), ('إلكترونية', 'إلكترونية'), ('دبوس', 'دبوس')], max_length=50, verbose_name='تصنيف الآلة')),
            ],
            options={
                'verbose_name': 'آلة موسيقية',
                'verbose_name_plural': 'الآلات الموسيقية',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='primary_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_players', to='em_data.musicalinstrument', verbose_name='الآلة الأساسية'),
        ),
        migrations.AddField(
            model_name='employee',
            name='secondary_instruments',
            field=models.ManyToManyField(blank=True, related_name='secondary_players', to='em_data.musicalinstrument', verbose_name='الآلات الفرعية'),
        ),
    ]
