# Generated by Django 5.1.4 on 2026-03-27 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0024_musicalinstrument_employee_primary_instrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='primary_instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_players', to='em_data.musicalinstrument', verbose_name='الآلة الموسيقية'),
        ),
    ]
