# Generated by Django 5.1.4 on 2025-11-22 10:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0010_alter_employee_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElawaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_number', models.CharField(max_length=100, verbose_name='رقم القرار')),
                ('elawa_date', models.DateField(verbose_name='تاريخ العلاوة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elawat', to='em_data.employee')),
            ],
            options={
                'verbose_name': 'سجل علاوة تشجيعية',
                'verbose_name_plural': 'سجلات العلاوات التشجيعية',
                'db_table': 'elawat_tashgeea_records',
                'ordering': ['-elawa_date', '-created_at'],
            },
        ),
    ]
