# Generated by Django 5.1.4 on 2026-03-02 09:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elawat_tashgeea', '0001_initial'),
        ('em_data', '0017_employee_mony_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elawarecord',
            name='decision_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم القرار'),
        ),
        migrations.CreateModel(
            name='NominationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='عام الترشيح')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='em_data.employee')),
            ],
            options={
                'verbose_name': 'ترشيح علاوة تشجيعية',
                'verbose_name_plural': 'ترشيحات العلاوة التشجيعية',
                'db_table': 'elawat_tashgeea_nominations',
                'unique_together': {('employee', 'year')},
            },
        ),
    ]
