# Generated by Django 4.1.12 on 2025-02-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_alter_institute_location_alter_institute_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='manager',
        ),
        migrations.AlterField(
            model_name='institute',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
