# Generated by Django 5.1.4 on 2025-10-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0010_alter_employee_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_year', models.IntegerField(help_text='العام الذي تُمنح فيه العلاوة (مثل 2025)', verbose_name='العام')),
                ('stored_value', models.DecimalField(decimal_places=2, help_text='القيمة المدخلة يدويًا أو تلقائيًا', max_digits=10, verbose_name='القيمة المخزنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_allowances', to='em_data.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'علاوة دورية',
                'verbose_name_plural': 'العلاوات الدورية',
                'ordering': ['-allowance_year'],
                'unique_together': {('employee', 'allowance_year')},
            },
        ),
    ]
