# Generated by Django 5.1.4 on 2025-10-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_allowances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicallowance',
            name='stored_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='القيمة المدخلة يدويًا أو تلقائيًا', max_digits=10, null=True, verbose_name='القيمة المخزنة'),
        ),
    ]
