# Generated by Django 5.1.4 on 2025-11-22 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0010_alter_employee_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم قرار الموافقة')),
                ('university_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الجامعة')),
                ('level', models.CharField(blank=True, choices=[('عالي', 'عالي'), ('فوق متوسط', 'فوق متوسط'), ('متوسط', 'متوسط'), ('اعدادي', 'اعدادي'), ('ابتدائي', 'ابتدائي')], max_length=50, null=True, verbose_name='مستوى المؤهل')),
                ('qualification_type', models.CharField(blank=True, choices=[('ليسانس حقوق', 'ليسانس حقوق'), ('دبلوم تجارة', 'دبلوم تجارة'), ('دبلوم صناعي', 'دبلوم صناعي'), ('دبلوم زراعي', 'دبلوم زراعي'), ('الاعدادية', 'الاعدادية'), ('الابتدائية', 'الابتدائية'), ('غير ذلك', 'غير ذلك')], max_length=255, null=True, verbose_name='نوع المؤهل')),
                ('grade', models.CharField(blank=True, choices=[('امتياز', 'امتياز'), ('جيد جدا', 'جيد جدا'), ('جيد', 'جيد'), ('مقبول', 'مقبول'), ('ضعيف', 'ضعيف')], max_length=50, null=True, verbose_name='التقدير')),
                ('obtained_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الحصول')),
                ('degree_validation_image', models.ImageField(blank=True, null=True, upload_to='education/validation/', verbose_name='صورة صحة المؤهل')),
                ('degree_image', models.ImageField(blank=True, null=True, upload_to='education/degrees/', verbose_name='صورة الشهادة')),
                ('ministry_approval_image', models.ImageField(blank=True, null=True, upload_to='education/approvals/', verbose_name='صورة موافقة الوزارة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='em_data.employee')),
            ],
            options={
                'verbose_name': 'مؤهل',
                'verbose_name_plural': 'المؤهلات',
                'db_table': 'education',
            },
        ),
    ]
