# Generated by Django 5.1.4 on 2025-11-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, choices=[('إمتياز', 'إمتياز'), ('جيد جدا', 'جيد جدا'), ('جيد', 'جيد'), ('مقبول', 'مقبول'), ('ضعيف', 'ضعيف')], max_length=50, null=True, verbose_name='التقدير'),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(blank=True, choices=[('عالي', 'عالي'), ('فوق متوسط', 'فوق متوسط'), ('متوسط', 'متوسط'), ('إعدادي', 'إعدادي'), ('إبتدائي', 'إبتدائي')], max_length=50, null=True, verbose_name='مستوى المؤهل'),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification_type',
            field=models.CharField(blank=True, choices=[('ليسانس حقوق', 'ليسانس حقوق'), ('دبلوم تجارة', 'دبلوم تجارة'), ('دبلوم صناعي', 'دبلوم صناعي'), ('دبلوم زراعي', 'دبلوم زراعي'), ('الإعدادية', 'الإعدادية'), ('الإبتدائية', 'الإبتدائية'), ('غير ذلك', 'غير ذلك')], max_length=255, null=True, verbose_name='نوع المؤهل'),
        ),
    ]
