# Generated by Django 4.1.12 on 2025-03-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('reminder_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('repeat', models.CharField(choices=[('none', 'غير متكررة'), ('daily', 'يومي'), ('monthly', 'شهري'), ('quarterly', 'كل 3 أشهر')], default='none', max_length=10)),
            ],
        ),
    ]
