# Generated by Django 5.1.4 on 2025-08-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_reminder_time_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='repeat',
            new_name='repeat_type',
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_interval',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
