# Generated by Django 5.1.4 on 2025-08-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_repeat_task_repeat_type_task_reminder_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='notes',
        ),
    ]
