# Generated by Django 5.1.4 on 2025-10-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options_alter_task_repeat_type_taskfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat_type',
            field=models.CharField(choices=[('none', 'غير متكررة'), ('daily', 'يومي'), ('monthly', 'شهري'), ('quarterly', 'كل 3 أشهر')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='file',
            field=models.FileField(upload_to='task_files/'),
        ),
    ]
