# Generated by Django 5.1.4 on 2025-12-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_options_alter_task_repeat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
