# Generated by Django 5.1.4 on 2025-11-24 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0010_alter_employee_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_count', models.IntegerField(blank=True, null=True, verbose_name='عدد أيام الإجازة')),
                ('duration_type', models.CharField(blank=True, choices=[('يوم', 'يوم'), ('شهر', 'شهر'), ('سنة', 'سنة')], max_length=10, null=True, verbose_name='نوع المدة')),
                ('leave_reason', models.CharField(choices=[('أجازة وضع', 'أجازة وضع'), ('رعاية طفل', 'رعاية طفل'), ('رعاية والده', 'رعاية والده'), ('رعاية والدته', 'رعاية والدته'), ('العمل مدرب موسيقي بدولة الكويت', 'العمل مدرب موسيقي بدولة الكويت')], max_length=100, verbose_name='سبب الإجازة')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ القيام')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='تاريخ العودة')),
                ('decision_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم القرار')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='السنة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_leaves', to='em_data.employee')),
            ],
            options={
                'db_table': 'special_leaves',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
