# Generated by Django 4.1.12 on 2025-03-11 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0005_employee_nots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmTrainingTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Training Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('result', models.CharField(blank=True, max_length=100, null=True, verbose_name='Result')),
                ('round_num', models.IntegerField(blank=True, null=True, verbose_name='Round Number')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_teams', to='em_data.employee', verbose_name='Employee')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_training_teams', to='training_teams.places', verbose_name='Place')),
                ('training_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_training_teams', to='training_teams.trainingteam', verbose_name='Training Team')),
            ],
            options={
                'verbose_name': 'Training Team',
                'verbose_name_plural': 'Training Teams',
            },
        ),
    ]
