# Generated by Django 4.1.12 on 2025-03-11 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0005_employee_nots'),
        ('training_teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emtrainingteams',
            options={'ordering': ['-start_date'], 'verbose_name': 'فريق تدريبي', 'verbose_name_plural': 'الفرق التدريبية'},
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_teams', to='em_data.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم التدريب'),
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_training_teams', to='training_teams.places', verbose_name='المكان'),
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='result',
            field=models.CharField(blank=True, choices=[('ناجح', 'ناجح'), ('راسب', 'راسب')], max_length=10, null=True, verbose_name='النتيجة'),
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='round_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الدورة'),
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='training_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_training_teams', to='training_teams.trainingteam', verbose_name='فريق التدريب'),
        ),
        migrations.AlterField(
            model_name='places',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='places',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم المكان'),
        ),
        migrations.AlterField(
            model_name='trainingteam',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='trainingteam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الفريق التدريبي'),
        ),
        migrations.AddConstraint(
            model_name='emtrainingteams',
            constraint=models.UniqueConstraint(fields=('employee', 'training_team', 'start_date', 'end_date'), name='unique_employee_training_period'),
        ),
    ]
