# Generated by Django 5.1.4 on 2026-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_teams', '0002_alter_emtrainingteams_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emtrainingteams',
            name='note',
            field=models.TextField(default='', verbose_name='ملاحظات'),
        ),
    ]
