# Generated by Django 5.1.4 on 2026-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_teams', '0003_emtrainingteams_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='emtrainingteams',
            name='success_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='training_certificates/', verbose_name='صورة إخطار النجاح'),
        ),
        migrations.AlterField(
            model_name='emtrainingteams',
            name='result',
            field=models.CharField(blank=True, choices=[('إنتظار', 'إنتظار'), ('ناجح', 'ناجح'), ('راسب', 'راسب')], max_length=10, null=True, verbose_name='النتيجة'),
        ),
    ]
