# Generated by Django 5.1.4 on 2026-03-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0019_employee_batch_number'),
        ('training_teams', '0004_emtrainingteams_success_certificate_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التدريب الدوري')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
        ),
        migrations.CreateModel(
            name='EmPeriodicTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('round_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الدورة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodic_trainings', to='em_data.employee', verbose_name='الموظف')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_periodic_trainings', to='training_teams.places', verbose_name='المكان')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_periodic_trainings', to='training_teams.periodictraining', verbose_name='نوع التدريب الدوري')),
            ],
            options={
                'verbose_name': 'سجل تدريب دوري',
                'verbose_name_plural': 'سجلات التدريب الدوري',
                'ordering': ['-start_date'],
            },
        ),
    ]
