# Generated by Django 5.1.4 on 2026-03-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_data', '0019_employee_batch_number'),
        ('training_teams', '0005_periodictraining_emperiodictraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualifyingTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفرقة التأهيلية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
        ),
        migrations.CreateModel(
            name='EmQualifyingTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('round_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الدورة')),
                ('result', models.CharField(blank=True, choices=[('إنتظار', 'إنتظار'), ('ناجح', 'ناجح'), ('راسب', 'راسب')], max_length=10, null=True, verbose_name='النتيجة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifying_trainings', to='em_data.employee', verbose_name='الموظف')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_qualifying_trainings', to='training_teams.places', verbose_name='المكان')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='em_qualifying_trainings', to='training_teams.qualifyingtraining', verbose_name='نوع الفرقة التأهيلية')),
            ],
            options={
                'verbose_name': 'سجل فرقة تأهيلية',
                'verbose_name_plural': 'سجلات الفرق التأهيلية',
                'ordering': ['-start_date'],
            },
        ),
    ]
