# Generated by Django 4.1.12 on 2025-02-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('em_data', '0005_employee_nots'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('state', models.CharField(choices=[('_', '-'), ('نوبتجي', 'نوبتجي'), ('يومي', 'يومي'), ('راحة', 'راحة'), ('دورية', 'دورية'), ('ر بديلة', 'ر بديلة'), ('طارئة', 'طارئة'), ('مأمورية', 'مأمورية'), ('مأمورية خ', 'مأمورية خ'), ('فرقة', 'فرقة'), ('انتداب', 'انتداب'), ('مرضي', 'مرضي'), ('ج وضع', 'ج وضع'), ('خاصه', 'خاصه'), ('8 صباحاً', '8 صباحاً'), ('ت دوري', 'ت دوري'), ('ت تكراري', 'ت تكراري'), ('منحة', 'منحة'), ('عطلة', 'عطلة'), ('غياب', 'غياب'), ('قرار66', 'قرار66')], default='_', max_length=20, verbose_name='حالة الحضور')),
                ('food', models.BooleanField(default=False, verbose_name='تعيين طعام')),
                ('comfort_adjustment', models.IntegerField(choices=[(0, 'لا تغيير'), (1, '+1'), (-1, '-1')], default=0, verbose_name='تعديل رصيد الراحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='em_data.employee', verbose_name='الفرد')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'سجل الحضور',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
