# Generated by Django 4.1.12 on 2025-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='in_or_out',
            field=models.CharField(choices=[('in', 'In'), ('going', 'Going'), ('out', 'Out')], default='out', max_length=10),
        ),
    ]
