# Generated by Django 4.1.12 on 2025-03-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_in_or_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='in_or_out',
            field=models.CharField(choices=[('in', 'In'), ('going', 'Going'), ('out', 'Out')], default='', max_length=10),
        ),
    ]
