# Generated by Django 5.1.4 on 2026-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendanceredolog'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
